//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetails
    {
        public int AttndncDtlsId { get; set; }
        public int AttndncMastrId { get; set; }
        public int MenteeId { get; set; }
        public double Hours { get; set; }
    
        public virtual AttendanceMaster AttendanceMaster { get; set; }
        public virtual Person Person { get; set; }
    }
}
