//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceMaster()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetails>();
        }
    
        public int AttndncMastrId { get; set; }
        public int MentorId { get; set; }
        public System.DateTime Date { get; set; }
        public string TrainingOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDetails> AttendanceDetails { get; set; }
        public virtual Person Person { get; set; }
    }
}
